In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib

In [27]:
data = pd.read_csv('expresso_processed.csv')
data.head()

,Unnamed: 0,TENURE,MONTANT,FREQUENCE_RECH,REVENUE,ARPU_SEGMENT,FREQUENCE,DATA_VOLUME,ON_NET,MRG,REGULARITY,CHURN
0,0,K > 24 month,3000.0,4.0,3002.0,1001.0,8.0,266.0,1.0,NO,32,1
1,1,K > 24 month,1500.0,3.0,1980.0,660.0,5.0,4341.0,1.0,NO,29,1
2,2,K > 24 month,9850.0,32.0,9639.0,3213.0,38.0,2700.0,4.0,NO,49,1
3,3,I 18-21 month,1000.0,2.0,999.0,333.0,2.0,763.0,8.0,NO,1,1
4,4,K > 24 month,1200.0,3.0,1180.0,393.0,3.0,2955.0,28.0,NO,21,1

In [28]:

for i in data.columns:
    if (data[i].isnull().sum() / len(data) * 100) < 30:
        if data[i].dtypes != 'O':
            data[i] = data[i].fillna(data[i].median())
        else:
            data[i] = data[i].fillna(data[i].mode()[0])
    else:
        data.drop(i, axis=1, inplace=True)

data.isnull().sum()

Unnamed: 0        0
TENURE            0
MONTANT           0
FREQUENCE_RECH    0
REVENUE           0
ARPU_SEGMENT      0
FREQUENCE         0
DATA_VOLUME       0
ON_NET            0
MRG               0
REGULARITY        0
CHURN             0
dtype: int64

In [29]:
data.drop(['Unnamed: 0', "TENURE", "ARPU_SEGMENT", "MRG"], axis=1, inplace=True)

In [30]:
data.head()

,MONTANT,FREQUENCE_RECH,REVENUE,FREQUENCE,DATA_VOLUME,ON_NET,REGULARITY,CHURN
0,3000.0,4.0,3002.0,8.0,266.0,1.0,32,1
1,1500.0,3.0,1980.0,5.0,4341.0,1.0,29,1
2,9850.0,32.0,9639.0,38.0,2700.0,4.0,49,1
3,1000.0,2.0,999.0,2.0,763.0,8.0,1,1
4,1200.0,3.0,1180.0,3.0,2955.0,28.0,21,1

In [31]:
cat = data.select_dtypes(exclude="number")
num = data.select_dtypes(include="number")

print("Categorical data\n\n")
display(cat.head())

print("")
print("")
print("Numerical Data \n\n")
display(num.head())

Categorical data

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

Numerical Data

,MONTANT,FREQUENCE_RECH,REVENUE,FREQUENCE,DATA_VOLUME,ON_NET,REGULARITY,CHURN
0,3000.0,4.0,3002.0,8.0,266.0,1.0,32,1
1,1500.0,3.0,1980.0,5.0,4341.0,1.0,29,1
2,9850.0,32.0,9639.0,38.0,2700.0,4.0,49,1
3,1000.0,2.0,999.0,2.0,763.0,8.0,1,1
4,1200.0,3.0,1180.0,3.0,2955.0,28.0,21,1

In [32]:
data.isnull().sum()

MONTANT           0
FREQUENCE_RECH    0
REVENUE           0
FREQUENCE         0
DATA_VOLUME       0
ON_NET            0
REGULARITY        0
CHURN             0
dtype: int64

In [33]:
data.head()

,MONTANT,FREQUENCE_RECH,REVENUE,FREQUENCE,DATA_VOLUME,ON_NET,REGULARITY,CHURN
0,3000.0,4.0,3002.0,8.0,266.0,1.0,32,1
1,1500.0,3.0,1980.0,5.0,4341.0,1.0,29,1
2,9850.0,32.0,9639.0,38.0,2700.0,4.0,49,1
3,1000.0,2.0,999.0,2.0,763.0,8.0,1,1
4,1200.0,3.0,1180.0,3.0,2955.0,28.0,21,1

In [34]:
# plt.plot(data=data)

In [35]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
import joblib

df = data.copy()
column_to_drop = ["CHURN"]

for col in df.drop(column_to_drop, axis=1).columns:
    if df[col].dtype in ["int64", "float64"]:
        scaler = StandardScaler()
        df[col] = scaler.fit_transform(df[[col]])
        scaler_path = f"scalers/{col}_scaler.pkl"
        print(f"Saving scaler for '{col}' to: {scaler_path}")
        joblib.dump(scaler, open(f"{scaler_path}", "wb"))
    else:
        encoder = LabelEncoder()
        df[col] = encoder.fit_transform(df[col])
        encoder_path = f"encoders/{col}_encoder.pkl"
        print(f"Saving encoder for '{col}' to: {encoder_path}")
        joblib.dump(encoder, open(f"{encoder_path}", "wb"))

df.head()

Saving scaler for 'MONTANT' to: scalers/MONTANT_scaler.pkl
Saving scaler for 'FREQUENCE_RECH' to: scalers/FREQUENCE_RECH_scaler.pkl
Saving scaler for 'REVENUE' to: scalers/REVENUE_scaler.pkl
Saving scaler for 'FREQUENCE' to: scalers/FREQUENCE_scaler.pkl
Saving scaler for 'DATA_VOLUME' to: scalers/DATA_VOLUME_scaler.pkl
Saving scaler for 'ON_NET' to: scalers/ON_NET_scaler.pkl
Saving scaler for 'REGULARITY' to: scalers/REGULARITY_scaler.pkl

,MONTANT,FREQUENCE_RECH,REVENUE,FREQUENCE,DATA_VOLUME,ON_NET,REGULARITY,CHURN
0,-0.304123,-0.530800,-0.314144,-0.375492,-0.380804,-0.288388,-0.058608,1
1,-0.525441,-0.610858,-0.461982,-0.589948,0.138867,-0.288388,-0.205435,1
2,0.706564,1.710845,0.645935,1.769067,-0.070404,-0.284413,0.773409,1
3,-0.599214,-0.690917,-0.603890,-0.804404,-0.317423,-0.279113,-1.575816,1
4,-0.569705,-0.610858,-0.577707,-0.732919,-0.037885,-0.252614,-0.596972,1

In [36]:
# df = df.drop(["TENURE", "ARPU_SEGMENT"], axis=1)
# df.head()

In [37]:
from sklearn.model_selection import train_test_split

x = df.drop("CHURN", axis=1)     # Features (everything except "CHURN")
y = df["CHURN"]                  # Target variable ("CHURN")

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=40)

In [38]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

model = LogisticRegression()

model.fit(xtrain, ytrain)

y_pred = model.predict(xtrain)

print(f"Accuracy: {accuracy_score(ytrain, y_pred):.2f}")
print("Classification Report:")
print(classification_report(ytrain, y_pred))

Accuracy: 0.77
Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.78      0.79     27958
           1       0.74      0.76      0.75     23542

    accuracy                           0.77     51500
   macro avg       0.77      0.77      0.77     51500
weighted avg       0.77      0.77      0.77     51500

In [39]:
test_pred = model.predict(xtest)
print(f"Test Score is: {accuracy_score(ytest, test_pred)}")

Test Score is: 0.7729885057471264

In [40]:

data.head()

,MONTANT,FREQUENCE_RECH,REVENUE,FREQUENCE,DATA_VOLUME,ON_NET,REGULARITY,CHURN
0,3000.0,4.0,3002.0,8.0,266.0,1.0,32,1
1,1500.0,3.0,1980.0,5.0,4341.0,1.0,29,1
2,9850.0,32.0,9639.0,38.0,2700.0,4.0,49,1
3,1000.0,2.0,999.0,2.0,763.0,8.0,1,1
4,1200.0,3.0,1180.0,3.0,2955.0,28.0,21,1

In [41]:
data.to_csv("data/expresso_processed_final.csv", index=False)
joblib.dump(model, open("models/expresso_processed_final.pkl", "wb"))

In [42]:
data.head()

,MONTANT,FREQUENCE_RECH,REVENUE,FREQUENCE,DATA_VOLUME,ON_NET,REGULARITY,CHURN
0,3000.0,4.0,3002.0,8.0,266.0,1.0,32,1
1,1500.0,3.0,1980.0,5.0,4341.0,1.0,29,1
2,9850.0,32.0,9639.0,38.0,2700.0,4.0,49,1
3,1000.0,2.0,999.0,2.0,763.0,8.0,1,1
4,1200.0,3.0,1180.0,3.0,2955.0,28.0,21,1

In [43]:
type(model)

sklearn.linear_model._logistic.LogisticRegression